#!/bin/bash
killall conky
conky -c ~/.conky/ConkyBar/configs/conky_bg &
conky -c ~/.conky/ConkyBar/configs/conky_clock &
conky -c ~/.conky/ConkyBar/configs/conky_txt &
conky -p 2 -c ~/.conky/ConkyBar/configs/conky_network2 &
conky -p 3 -c ~/.conky/ConkyBar/configs/conky_banshee4 &
conky -p 5 -c ~/.conky/ConkyBar/configs/conky_system2 &
conky -p 6 -c ~/.conky/ConkyBar/configs/conky_cpu &
conky -p 7 -c ~/.conky/ConkyBar/configs/conky_ram &
conky -p 8 -c ~/.conky/ConkyBar/configs/conky_files2
exit
